version: "3.8"
services:
  gmod-ssh-sidecar:
    build: .
    container_name: gmod-ssh-sidecar
    environment:
      SSH_PUBKEY: ${SSH_PUBKEY}
      PTERO_UUID: ${PTERO_UUID}
    ports:
      - "2222:22"   # change if needed
    restart: unless-stopped
